// Seed products (ADR-008 D5): common meeting-room AV and furniture so a fresh install can furnish a
// room. Dimensions and specs come from general product knowledge, not from fetched spec sheets, so
// every real product starts `unverified`; verify_product upgrades a record with sources (ADR-008 D3).
// The Generic entries are parametric placeholders and are `manual`: a door, a window, and furniture that
// can be drawn at any size, where every branded piece comes in the one size it is sold in (F-013).
import type { ProductInput } from "../schema.js";

const AT = "2026-09-15T00:00:00.000Z";
const UNVERIFIED: ProductInput["verification"] = {
  status: "unverified",
  confidence: 0.5,
  sources: [],
  verifiedAt: null,
  notes: "Seed record from general product knowledge; run verify_product before quoting.",
};
const MANUAL: ProductInput["verification"] = {
  status: "manual",
  confidence: 1,
  sources: [],
  verifiedAt: AT,
  notes: "Built-in parametric placeholder, not a purchasable product.",
};

type Seed = Omit<ProductInput, "createdAt" | "updatedAt" | "verification"> & {
  verification?: ProductInput["verification"];
};

function seed(p: Seed): ProductInput {
  return { verification: UNVERIFIED, ...p, createdAt: AT, updatedAt: AT };
}

const display = (
  id: string,
  make: string,
  model: string,
  diagonalIn: number,
  dims: { w: number; d: number; h: number },
  weightKg: number,
  vesa: string,
  powerW: number,
): ProductInput =>
  seed({
    id,
    make,
    model,
    name: `${make} ${model} ${diagonalIn} inch 4K display`,
    category: "display",
    dims,
    weightKg,
    mount: { kinds: ["wall", "floor"], vesa, defaultHeight: 1100 },
    mountPoints: [],
    deformable: false,
    specs: { diagonalIn, resolution: "3840x2160", vesa, powerW },
    lifecycle: "active",
    tags: ["display", "4k", "large-format", "meeting"],
    aliases: ["tv", "screen", `${diagonalIn} inch`],
  });

const videoBar = (
  id: string,
  make: string,
  model: string,
  dims: { w: number; d: number; h: number },
  fovDeg: number,
  maxRoomDepthMm: number,
  interfaces: string,
  tags: string[],
): ProductInput =>
  seed({
    id,
    make,
    model,
    name: `${make} ${model} video bar`,
    category: "video-bar",
    dims,
    mount: { kinds: ["wall", "table"], vesa: null, defaultHeight: 1400 },
    mountPoints: [],
    deformable: false,
    specs: { fovDeg, maxRoomDepthMm, interfaces },
    lifecycle: "active",
    tags: ["video-bar", "video conferencing", "camera", ...tags],
    aliases: ["videobar", "conference camera", "collaboration bar"],
  });

export const SEED_PRODUCTS: ProductInput[] = [
  display("samsung-qm75c", "Samsung", "QM75C", 75, { w: 1672, d: 45, h: 962 }, 32, "400x400", 210),
  display("samsung-qm85c", "Samsung", "QM85C", 85, { w: 1899, d: 47, h: 1091 }, 46, "600x400", 300),
  display("samsung-qm98c", "Samsung", "QM98C", 98, { w: 2190, d: 88, h: 1252 }, 82, "800x400", 500),
  display("lg-75uh5j", "LG", "75UH5J", 75, { w: 1679, d: 70, h: 969 }, 33, "400x400", 225),
  display("lg-86uh5j", "LG", "86UH5J", 86, { w: 1927, d: 70, h: 1108 }, 45, "600x400", 300),
  videoBar(
    "logitech-rally-bar",
    "Logitech",
    "Rally Bar",
    { w: 1092, d: 125, h: 136 },
    90,
    7000,
    "USB-C, HDMI, Ethernet",
    ["large room"],
  ),
  videoBar(
    "logitech-rally-bar-mini",
    "Logitech",
    "Rally Bar Mini",
    { w: 668, d: 120, h: 121 },
    90,
    5000,
    "USB-C, HDMI, Ethernet",
    ["medium room"],
  ),
  videoBar(
    "poly-studio-x52",
    "Poly",
    "Studio X52",
    { w: 736, d: 105, h: 106 },
    95,
    6000,
    "HDMI, Ethernet, USB",
    ["medium room"],
  ),
  videoBar(
    "yealink-meetingbar-a30",
    "Yealink",
    "MeetingBar A30",
    { w: 750, d: 84, h: 95 },
    120,
    5000,
    "HDMI, Ethernet, USB",
    ["medium room"],
  ),
  seed({
    id: "shure-mxa920-s",
    make: "Shure",
    model: "MXA920-S",
    name: "Shure MXA920 square ceiling array microphone",
    category: "ceiling-mic",
    dims: { w: 600, d: 600, h: 55 },
    weightKg: 5.4,
    mount: { kinds: ["ceiling"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { coverageRadiusMm: 4500, channels: 8, dante: true, poe: true },
    lifecycle: "active",
    tags: ["ceiling-mic", "microphone", "array", "dante", "meeting"],
    aliases: ["ceiling microphone", "mic array", "mxa920"],
  }),
  seed({
    id: "sennheiser-tcc2",
    make: "Sennheiser",
    model: "TeamConnect Ceiling 2",
    name: "Sennheiser TeamConnect Ceiling 2 beamforming microphone",
    category: "ceiling-mic",
    dims: { w: 600, d: 600, h: 30 },
    weightKg: 5.5,
    mount: { kinds: ["ceiling"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { coverageRadiusMm: 4500, channels: 1, dante: true, poe: true },
    lifecycle: "active",
    tags: ["ceiling-mic", "microphone", "beamforming", "dante", "meeting"],
    aliases: ["tcc2", "ceiling microphone"],
  }),
  seed({
    id: "shure-mxa310",
    make: "Shure",
    model: "MXA310",
    name: "Shure MXA310 table array microphone",
    category: "table-mic",
    dims: { w: 105, d: 105, h: 30 },
    mount: { kinds: ["table"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { coverageRadiusMm: 2000, channels: 4, dante: true },
    lifecycle: "active",
    tags: ["table-mic", "microphone", "array", "dante"],
    aliases: ["table microphone", "boundary mic"],
  }),
  seed({
    id: "biamp-desono-c-ic6",
    make: "Biamp",
    model: "Desono C-IC6",
    name: "Biamp Desono C-IC6 6.5 inch ceiling speaker",
    category: "ceiling-speaker",
    dims: { w: 250, d: 250, h: 190 },
    weightKg: 2.3,
    mount: { kinds: ["ceiling"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { coverageRadiusMm: 3000, impedanceOhm: 8, powerW: 30, transformer70V: true },
    lifecycle: "active",
    tags: ["ceiling-speaker", "speaker", "meeting"],
    aliases: ["in-ceiling speaker", "loudspeaker"],
  }),
  seed({
    id: "qsc-ad-c6t",
    make: "QSC",
    model: "AD-C6T",
    name: "QSC AcousticDesign AD-C6T 6.5 inch ceiling speaker",
    category: "ceiling-speaker",
    dims: { w: 280, d: 280, h: 220 },
    weightKg: 3.6,
    mount: { kinds: ["ceiling"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { coverageRadiusMm: 3500, impedanceOhm: 8, powerW: 60, transformer70V: true },
    lifecycle: "active",
    tags: ["ceiling-speaker", "speaker", "meeting"],
    aliases: ["in-ceiling speaker", "loudspeaker"],
  }),
  seed({
    id: "jbl-control-26ct",
    make: "JBL",
    model: "Control 26CT",
    name: "JBL Control 26CT 6.5 inch ceiling speaker",
    category: "ceiling-speaker",
    dims: { w: 270, d: 270, h: 210 },
    weightKg: 3.4,
    mount: { kinds: ["ceiling"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { coverageRadiusMm: 3500, impedanceOhm: 8, powerW: 150, transformer70V: true },
    lifecycle: "active",
    tags: ["ceiling-speaker", "speaker"],
    aliases: ["in-ceiling speaker", "loudspeaker"],
  }),
  seed({
    id: "logitech-tap-scheduler",
    make: "Logitech",
    model: "Tap Scheduler",
    name: "Logitech Tap Scheduler room booking panel",
    category: "scheduler",
    dims: { w: 244, d: 30, h: 162 },
    mount: { kinds: ["wall"], vesa: null, defaultHeight: 1400 },
    deformable: false,
    specs: { screenIn: 10.1, poe: true },
    lifecycle: "active",
    tags: ["scheduler", "room booking", "panel", "meeting"],
    aliases: ["room panel", "booking panel", "scheduling panel"],
  }),
  seed({
    id: "crestron-tss-770",
    make: "Crestron",
    model: "TSS-770",
    name: "Crestron TSS-770 7 inch room scheduling touch screen",
    category: "scheduler",
    dims: { w: 190, d: 30, h: 130 },
    mount: { kinds: ["wall"], vesa: null, defaultHeight: 1400 },
    deformable: false,
    specs: { screenIn: 7, poe: true },
    lifecycle: "active",
    tags: ["scheduler", "room booking", "panel"],
    aliases: ["room panel", "booking panel"],
  }),
  seed({
    id: "logitech-tap-ip",
    make: "Logitech",
    model: "Tap IP",
    name: "Logitech Tap IP touch controller",
    category: "touch-panel",
    dims: { w: 244, d: 120, h: 174 },
    mount: { kinds: ["table"], vesa: null, defaultHeight: null },
    deformable: false,
    specs: { screenIn: 10.1, poe: true },
    lifecycle: "active",
    tags: ["touch-panel", "controller", "meeting"],
    aliases: ["touch controller", "room controller"],
  }),
  seed({
    id: "steelcase-convene-3600x1400",
    make: "Steelcase",
    model: "Convene 3600 x 1400",
    name: "Steelcase Convene boardroom table 3600 x 1400",
    category: "table",
    dims: { w: 3600, d: 1400, h: 740 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [{ name: "top", kind: "surface", dropRatio: 1, offset: null }],
    clearance: { front: 900, back: 900, left: 900, right: 900 },
    deformable: false,
    specs: { seats: 12, shape: "rect" },
    lifecycle: "active",
    tags: ["table", "boardroom", "meeting"],
    aliases: ["boardroom table", "conference table"],
  }),
  seed({
    id: "steelcase-convene-2400x1200",
    make: "Steelcase",
    model: "Convene 2400 x 1200",
    name: "Steelcase Convene meeting table 2400 x 1200",
    category: "table",
    dims: { w: 2400, d: 1200, h: 740 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [{ name: "top", kind: "surface", dropRatio: 1, offset: null }],
    clearance: { front: 900, back: 900, left: 900, right: 900 },
    deformable: false,
    specs: { seats: 8, shape: "rect" },
    lifecycle: "active",
    tags: ["table", "meeting"],
    aliases: ["meeting table", "conference table"],
  }),
  seed({
    id: "herman-miller-everywhere-round-1200",
    make: "Herman Miller",
    model: "Everywhere round 1200",
    name: "Herman Miller Everywhere round table 1200",
    category: "table",
    dims: { w: 1200, d: 1200, h: 720 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [{ name: "top", kind: "surface", dropRatio: 1, offset: null }],
    clearance: { front: 750, back: 750, left: 750, right: 750 },
    deformable: false,
    specs: { seats: 4, shape: "round" },
    lifecycle: "active",
    tags: ["table", "huddle", "round"],
    aliases: ["huddle table", "round table"],
  }),
  seed({
    id: "herman-miller-aeron-b",
    make: "Herman Miller",
    model: "Aeron size B",
    name: "Herman Miller Aeron chair size B",
    category: "chair",
    dims: { w: 686, d: 640, h: 1040 },
    weightKg: 19,
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [],
    deformable: false,
    specs: { armrests: true, swivel: true },
    lifecycle: "active",
    tags: ["chair", "task chair", "boardroom"],
    aliases: ["office chair", "task chair", "aeron"],
  }),
  seed({
    id: "steelcase-series-1",
    make: "Steelcase",
    model: "Series 1",
    name: "Steelcase Series 1 task chair",
    category: "chair",
    dims: { w: 622, d: 572, h: 1030 },
    weightKg: 14,
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [],
    deformable: false,
    specs: { armrests: true, swivel: true },
    lifecycle: "active",
    tags: ["chair", "task chair", "training"],
    aliases: ["office chair", "task chair"],
  }),
  seed({
    id: "steelcase-gesture",
    make: "Steelcase",
    model: "Gesture",
    name: "Steelcase Gesture chair",
    category: "chair",
    dims: { w: 610, d: 610, h: 1120 },
    weightKg: 25,
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [],
    deformable: false,
    specs: { armrests: true, swivel: true },
    lifecycle: "active",
    tags: ["chair", "task chair", "boardroom"],
    aliases: ["office chair", "executive chair"],
  }),
  seed({
    id: "quartet-infinity-1800x1200",
    make: "Quartet",
    model: "Infinity 1800 x 1200",
    name: "Quartet Infinity glass whiteboard 1800 x 1200",
    category: "whiteboard",
    dims: { w: 1800, d: 20, h: 1200 },
    mount: { kinds: ["wall"], vesa: null, defaultHeight: 900 },
    deformable: false,
    specs: { surface: "glass", magnetic: true },
    lifecycle: "active",
    tags: ["whiteboard", "glass board"],
    aliases: ["glass board", "dry erase board", "writing surface"],
  }),
  seed({
    id: "steelcase-universal-credenza-1800",
    make: "Steelcase",
    model: "Universal credenza 1800",
    name: "Steelcase Universal storage credenza 1800",
    category: "storage",
    dims: { w: 1800, d: 600, h: 720 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [{ name: "top", kind: "surface", dropRatio: 1, offset: null }],
    deformable: false,
    specs: { doors: 4 },
    lifecycle: "active",
    tags: ["storage", "credenza", "boardroom"],
    aliases: ["credenza", "sideboard", "cabinet"],
  }),
  seed({
    id: "generic-table-1800x900",
    make: "Generic",
    model: "Table",
    name: "Generic table, any size",
    category: "table",
    dims: { w: 1800, d: 900, h: 740 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [{ name: "top", kind: "surface", dropRatio: 1, offset: null }],
    clearance: { front: 900, back: 900, left: 900, right: 900 },
    deformable: true,
    specs: { seats: 6, shape: "rect" },
    verification: MANUAL,
    lifecycle: "active",
    tags: ["table", "meeting", "generic"],
    aliases: ["table", "meeting table", "custom table"],
  }),
  seed({
    id: "generic-desk-1600x800",
    make: "Generic",
    model: "Desk",
    name: "Generic desk, any size",
    category: "desk",
    dims: { w: 1600, d: 800, h: 740 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [{ name: "top", kind: "surface", dropRatio: 1, offset: null }],
    clearance: { front: 1000, back: 0, left: 0, right: 0 },
    deformable: true,
    specs: { seats: 1 },
    verification: MANUAL,
    lifecycle: "active",
    tags: ["desk", "workstation", "generic"],
    aliases: ["desk", "workstation", "custom desk"],
  }),
  seed({
    id: "generic-chair",
    make: "Generic",
    model: "Chair",
    name: "Generic chair, any size",
    category: "chair",
    dims: { w: 600, d: 600, h: 900 },
    mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
    mountPoints: [],
    deformable: true,
    specs: {},
    verification: MANUAL,
    lifecycle: "active",
    tags: ["chair", "generic"],
    aliases: ["chair", "seat", "custom chair"],
  }),
  // Residential generics: the shapes a home is furnished with, at the sizes they are commonly sold in.
  // Placeholders like the ones above, so a dwelling can be drawn and priced before a brand is chosen.
  ...(
    [
      ["generic-bed-single", "Single bed", "bed", { w: 900, d: 2000, h: 900 }, { size: "single", sleeps: 1 }],
      [
        "generic-bed-double",
        "Double bed",
        "bed",
        { w: 1350, d: 2000, h: 900 },
        { size: "double", sleeps: 2 },
      ],
      ["generic-bed-queen", "Queen bed", "bed", { w: 1500, d: 2000, h: 900 }, { size: "queen", sleeps: 2 }],
      ["generic-bed-king", "King bed", "bed", { w: 1800, d: 2000, h: 900 }, { size: "king", sleeps: 2 }],
      ["generic-wardrobe-1200", "Wardrobe 1200", "wardrobe", { w: 1200, d: 600, h: 2100 }, { doors: 2 }],
      ["generic-wardrobe-1800", "Wardrobe 1800", "wardrobe", { w: 1800, d: 600, h: 2100 }, { doors: 3 }],
      ["generic-sofa-2", "Two-seat sofa", "sofa", { w: 1500, d: 900, h: 850 }, { seats: 2 }],
      ["generic-sofa-3", "Three-seat sofa", "sofa", { w: 2000, d: 900, h: 850 }, { seats: 3 }],
      ["generic-media-unit", "Media unit", "storage", { w: 1600, d: 450, h: 500 }, { doors: 2 }],
      [
        "generic-dining-table-6",
        "Dining table for 6",
        "table",
        { w: 1500, d: 900, h: 750 },
        { seats: 6, shape: "rect" },
      ],
      [
        "generic-dining-table-8",
        "Dining table for 8",
        "table",
        { w: 2000, d: 1000, h: 750 },
        { seats: 8, shape: "rect" },
      ],
      ["generic-dining-chair", "Dining chair", "chair", { w: 450, d: 500, h: 900 }, {}],
      [
        "generic-kitchen-run-2400",
        "Kitchen run 2400",
        "kitchen-run",
        { w: 2400, d: 600, h: 900 },
        { worktop: true },
      ],
      [
        "generic-kitchen-run-3000",
        "Kitchen run 3000",
        "kitchen-run",
        { w: 3000, d: 600, h: 900 },
        { worktop: true },
      ],
      ["generic-fridge", "Fridge freezer", "appliance", { w: 700, d: 700, h: 1800 }, { kind: "fridge" }],
      [
        "generic-washing-machine",
        "Washing machine",
        "appliance",
        { w: 600, d: 600, h: 850 },
        { kind: "washer" },
      ],
      ["generic-toilet", "Toilet", "sanitary", { w: 400, d: 650, h: 800 }, { kind: "wc" }],
      ["generic-basin", "Basin", "sanitary", { w: 550, d: 450, h: 850 }, { kind: "basin" }],
      ["generic-shower-900", "Shower 900", "sanitary", { w: 900, d: 900, h: 2000 }, { kind: "shower" }],
      ["generic-bath-1700", "Bath 1700", "sanitary", { w: 1700, d: 750, h: 550 }, { kind: "bath" }],
    ] as const
  ).map(([id, model, category, dims, specs]) =>
    seed({
      id,
      make: "Generic",
      model,
      name: `Generic ${model.toLowerCase()}`,
      category,
      dims,
      mount: { kinds: ["floor"], vesa: null, defaultHeight: null },
      mountPoints: [],
      deformable: true,
      specs: { ...specs },
      verification: MANUAL,
      lifecycle: "active",
      tags: [category, "generic", "residential"],
      aliases: [model.toLowerCase()],
    }),
  ),
  seed({
    id: "generic-door-900",
    make: "Generic",
    model: "Door 900",
    name: "Generic single door 900 x 2100",
    category: "door",
    dims: { w: 900, d: 40, h: 2100 },
    mount: { kinds: ["wall"], vesa: null, defaultHeight: null },
    mountPoints: [],
    deformable: true,
    opening: {
      embed: { thickness: 1, distance: 0, width: 1, left: 0, height: 1, top: 0 },
      cutOutPath: null,
      cutBothSides: true,
      sashes: [{ xAxis: 0, yAxis: 0, width: 1, startAngle: 0, endAngle: 90 }],
    },
    specs: { leaves: 1 },
    verification: MANUAL,
    lifecycle: "active",
    tags: ["door", "single"],
    aliases: ["single door", "office door"],
  }),
  seed({
    id: "generic-window-1200",
    make: "Generic",
    model: "Window 1200",
    name: "Generic window 1200 x 1200",
    category: "window",
    dims: { w: 1200, d: 40, h: 1200 },
    mount: { kinds: ["wall"], vesa: null, defaultHeight: 900 },
    mountPoints: [],
    deformable: true,
    opening: {
      embed: { thickness: 1, distance: 0, width: 1, left: 0, height: 1, top: 0 },
      cutOutPath: null,
      cutBothSides: true,
      sashes: [],
    },
    specs: { glazing: "double" },
    verification: MANUAL,
    lifecycle: "active",
    tags: ["window"],
    aliases: ["office window"],
  }),
];
