// The residential rules pack (spec 07 section 3.2): what a dwelling's rooms need, as data. It
// overlays the AV core pack, so one session holds both and a room is furnished by its purpose, not
// by which pack happened to load. Sizes are the common minimums of national housing standards,
// rounded to what a plan is drawn in; they are warnings, because a client's brief outranks a rule.

import { AV_CORE } from "./av-core.js";
import { mergePacks, RulesPack, type RulesPackInput } from "./schema.js";

export const HOME_CORE_INPUT: RulesPackInput = {
  id: "home-core",
  version: "1.0.0",
  name: "Residential core rules",
  extends: "av-core",
  facts: {
    bedroomMinM2: 9,
    bedroomMinSideMm: 2400,
    livingMinM2: 12,
    livingMinSideMm: 3000,
    kitchenMinM2: 5,
    kitchenMinSideMm: 1800,
    diningMinM2: 7,
    diningMinSideMm: 2400,
    bathroomMinM2: 3,
    bathroomMinSideMm: 1500,
    toiletMinM2: 1.2,
    toiletMinSideMm: 900,
    tvCentreHeightMm: 1100,
  },
  bomRules: [],
  designRules: [
    {
      id: "bedroom-size",
      applies: "room.purpose == 'bedroom'",
      check: "room.areaM2 >= bedroomMinM2 and room.minSideMm >= bedroomMinSideMm",
      message: "a bedroom needs at least 9 m² with a clear side of 2.4 m",
      hint: "widen the room or move the wall; a bed and a wardrobe do not fit in less",
    },
    {
      id: "living-size",
      applies: "room.purpose == 'living'",
      check: "room.areaM2 >= livingMinM2 and room.minSideMm >= livingMinSideMm",
      message: "a living room needs at least 12 m² with a clear side of 3 m",
      hint: "make the living room larger; it is where the household sits together",
    },
    {
      id: "kitchen-size",
      applies: "room.purpose == 'kitchen'",
      check: "room.areaM2 >= kitchenMinM2 and room.minSideMm >= kitchenMinSideMm",
      message: "a kitchen needs at least 5 m² with a clear side of 1.8 m",
      hint: "a kitchen run is 600 mm deep and needs 1.2 m of floor in front of it",
    },
    {
      id: "dining-size",
      applies: "room.purpose == 'dining'",
      check: "room.areaM2 >= diningMinM2 and room.minSideMm >= diningMinSideMm",
      message: "a dining room needs at least 7 m² with a clear side of 2.4 m",
      hint: "chairs need 900 mm behind them on every side of the table",
    },
    {
      id: "bathroom-size",
      applies: "room.purpose == 'bathroom'",
      check: "room.areaM2 >= bathroomMinM2 and room.minSideMm >= bathroomMinSideMm",
      message: "a bathroom needs at least 3 m² with a clear side of 1.5 m",
      hint: "a shower, a basin and a toilet along one wall take 2.4 m",
    },
    {
      id: "toilet-size",
      applies: "room.purpose == 'toilet'",
      check: "room.areaM2 >= toiletMinM2 and room.minSideMm >= toiletMinSideMm",
      message: "a toilet needs at least 1.2 m² and a clear width of 900 mm",
      hint: null,
    },
    {
      id: "tv-centre-height",
      applies: "room.purpose == 'living' and countWhere('display', 'mount', '==', 'wall') > 0",
      check: "abs(max('display', 'centreHeight') - tvCentreHeightMm) <= 250",
      message: "a living-room television is watched from a sofa, so its centre belongs near 1100 mm",
      hint: "set the display elevation so its centre is near 1100 mm",
    },
  ],
  // Residential recipes (spec 07 section 4.2). Beds and sofas have their backs to a wall, so most of
  // these are along-wall steps: the frame's wall is the one opposite the door, which is where a bed
  // or a television belongs; a wardrobe takes a side wall; a bathroom's fixtures share one wall.
  recipes: [
    {
      id: "bedroom-single",
      purpose: "bedroom",
      capacityRange: [1, 1],
      steps: [
        {
          op: "along-wall",
          category: "bed",
          wall: "auto",
          countExpr: "1",
          shape: "bed",
          sizeMm: { w: 900, d: 2000, h: 900 },
          label: "Single bed",
          spacingMm: 300,
          align: "centre",
          clearanceMm: 700,
        },
        {
          op: "along-wall",
          category: "wardrobe",
          wall: "beside-display",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 1200, d: 600, h: 2100 },
          label: "Wardrobe",
          spacingMm: 100,
          align: "end",
          clearanceMm: 600,
        },
      ],
      productPreferences: [
        { category: "bed", constraint: "w <= 1100", preferMake: [] },
        { category: "wardrobe", constraint: "w <= 1300", preferMake: [] },
      ],
    },
    {
      id: "bedroom",
      purpose: "bedroom",
      capacityRange: [2, 4],
      steps: [
        {
          op: "along-wall",
          category: "bed",
          wall: "auto",
          countExpr: "1",
          shape: "bed",
          sizeMm: { w: 1500, d: 2000, h: 900 },
          label: "Double bed",
          spacingMm: 500,
          align: "centre",
          clearanceMm: 700,
        },
        {
          op: "along-wall",
          category: "wardrobe",
          wall: "beside-display",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 1800, d: 600, h: 2100 },
          label: "Wardrobe",
          spacingMm: 100,
          align: "end",
          clearanceMm: 600,
        },
      ],
      productPreferences: [
        { category: "bed", constraint: "w >= 1350 and w <= 1600", preferMake: [] },
        { category: "wardrobe", constraint: "w >= 1500", preferMake: [] },
      ],
    },
    {
      id: "living",
      purpose: "living",
      capacityRange: [2, 8],
      steps: [
        {
          op: "along-wall",
          category: "storage",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 1600, d: 450, h: 500 },
          label: "TV unit",
          where: "h <= 600",
          spacingMm: 300,
          align: "centre",
          clearanceMm: 600,
        },
        { op: "display", wall: "auto", diagonalExpr: "55", centreHeightMm: 1100, countExpr: "1" },
        {
          op: "along-wall",
          category: "sofa",
          wall: "opposite-display",
          countExpr: "1",
          shape: "sofa",
          sizeMm: { w: 2000, d: 900, h: 850 },
          label: "Sofa",
          spacingMm: 300,
          align: "centre",
          clearanceMm: 1000,
        },
      ],
      productPreferences: [
        { category: "display", constraint: "diagonalIn >= 50 and diagonalIn <= 65", preferMake: [] },
        { category: "sofa", constraint: "w >= 1800", preferMake: [] },
        { category: "storage", constraint: "h <= 600", preferMake: [] },
      ],
    },
    {
      id: "kitchen",
      purpose: "kitchen",
      capacityRange: [0, 4],
      steps: [
        {
          op: "along-wall",
          category: "kitchen-run",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 2400, d: 600, h: 900 },
          label: "Kitchen run",
          spacingMm: 0,
          align: "start",
          clearanceMm: 1200,
        },
        {
          op: "along-wall",
          category: "appliance",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 700, d: 700, h: 1800 },
          label: "Fridge",
          where: "kind == 'fridge'",
          spacingMm: 50,
          align: "start",
          clearanceMm: 1000,
        },
      ],
      productPreferences: [{ category: "appliance", constraint: "h >= 1500", preferMake: [] }],
    },
    {
      id: "dining",
      purpose: "dining",
      capacityRange: [2, 12],
      steps: [
        { op: "table", shape: "rect", seatsExpr: "room.capacity", clearanceMm: 900 },
        { op: "chairs", around: "table", pitchMm: 600 },
      ],
      productPreferences: [
        {
          category: "table",
          constraint: "seats >= neededSeats and shape == 'rect' and d <= 1000",
          preferMake: [],
        },
        { category: "chair", constraint: "w <= 500", preferMake: [] },
      ],
    },
    {
      id: "bathroom",
      purpose: "bathroom",
      capacityRange: [0, 2],
      steps: [
        {
          op: "along-wall",
          category: "sanitary",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 900, d: 900, h: 2000 },
          label: "Shower",
          where: "kind == 'shower'",
          spacingMm: 0,
          align: "start",
          clearanceMm: 700,
        },
        {
          op: "along-wall",
          category: "sanitary",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 550, d: 450, h: 850 },
          label: "Basin",
          where: "kind == 'basin'",
          spacingMm: 150,
          align: "start",
          clearanceMm: 700,
        },
        {
          op: "along-wall",
          category: "sanitary",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 400, d: 650, h: 800 },
          label: "Toilet",
          where: "kind == 'wc'",
          spacingMm: 150,
          align: "start",
          clearanceMm: 600,
        },
      ],
      productPreferences: [],
    },
    {
      id: "toilet",
      purpose: "toilet",
      capacityRange: [0, 1],
      steps: [
        {
          op: "along-wall",
          category: "sanitary",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 400, d: 650, h: 800 },
          label: "Toilet",
          where: "kind == 'wc'",
          spacingMm: 100,
          align: "centre",
          clearanceMm: 600,
        },
        {
          op: "along-wall",
          category: "sanitary",
          wall: "beside-display",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 450, d: 380, h: 850 },
          label: "Basin",
          where: "kind == 'basin'",
          spacingMm: 100,
          align: "end",
          clearanceMm: 500,
        },
      ],
      productPreferences: [],
    },
    {
      id: "study",
      purpose: "study",
      capacityRange: [1, 2],
      steps: [
        {
          op: "along-wall",
          category: "desk",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 1400, d: 700, h: 740 },
          label: "Desk",
          spacingMm: 200,
          align: "centre",
          clearanceMm: 1000,
        },
        {
          op: "along-wall",
          category: "storage",
          wall: "beside-display",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 900, d: 350, h: 1800 },
          label: "Bookcase",
          where: "h >= 1200",
          spacingMm: 100,
          align: "end",
          clearanceMm: 600,
        },
      ],
      productPreferences: [{ category: "desk", constraint: "w <= 1800", preferMake: [] }],
    },
    {
      id: "laundry",
      purpose: "laundry",
      capacityRange: [0, 1],
      steps: [
        {
          op: "along-wall",
          category: "appliance",
          wall: "auto",
          countExpr: "1",
          shape: "box",
          sizeMm: { w: 600, d: 600, h: 850 },
          label: "Washing machine",
          where: "kind == 'washer'",
          spacingMm: 50,
          align: "start",
          clearanceMm: 900,
        },
      ],
      productPreferences: [{ category: "appliance", constraint: "h <= 1000", preferMake: [] }],
    },
    // Rooms that are furnished by their emptiness: nothing to place, and nothing borrowed from a
    // neighbouring recipe by capacity alone.
    { id: "foyer", purpose: "foyer", capacityRange: [0, 99], steps: [], productPreferences: [] },
    { id: "balcony", purpose: "balcony", capacityRange: [0, 99], steps: [], productPreferences: [] },
    { id: "garage", purpose: "garage", capacityRange: [0, 99], steps: [], productPreferences: [] },
    { id: "corridor", purpose: "corridor", capacityRange: [0, 99], steps: [], productPreferences: [] },
  ],
};

export const HOME_CORE: RulesPack = RulesPack.parse(HOME_CORE_INPUT);

/** Both built-in packs as one: what a session loads unless a user's pack says otherwise. */
export const CORE_RULES: RulesPack = mergePacks(AV_CORE, HOME_CORE);
